[deploy.maven.mavenCentral.sonatype]
active = "ALWAYS"
applyMavenCentralRules = false
sign = false
stagingRepositories = ["build/maven"]
url = "https://central.sonatype.com/api/v1/publisher"
verifyPom = false
